create table movies(
 movie_id int not null primary key,
 title varchar(50),
 user_rate int,
 imdb_rate decimal(10,5),
 years int,
 img_url varchar(600),
 plot varchar(500),
 runtime int
 );



insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(1,"The Godfather" , 9, 9.2 ,1972, "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", "The aging patriarch of an organized crime dynasty transfers of his clandestime empire to his reluctant son." , 175);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(2,"The Shawshank Redemption",9 ,9.3 ,1994,"https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg", "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",142);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(3,"The Dark Knight",9,9,2008,"https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_UX182_CR0,0,182,268_AL_.jpg","When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",152);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(4,"Avengers: Infinity War",8,8.5,2018,"https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_UY209_CR0,0,140,209_AL_.jpg","The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",149);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(5,"Logan",8,8.1,2017,"https://m.media-amazon.com/images/M/MV5BYzc5MTU4N2EtYTkyMi00NjdhLTg3NWEtMTY4OTEyMzJhZTAzXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX140_CR0,0,140,209_AL_.jpg","In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety",137);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(6,"Guardians of the Galaxy" ,8,8.1,2014,"https://m.media-amazon.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_UY209_CR0,0,140,209_AL_.jpg","A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",121);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(7,"Guardians of the Galaxy Vol.2",7,7.7,2017,"https://m.media-amazon.com/images/M/MV5BMTg2MzI1MTg3OF5BMl5BanBnXkFtZTgwNTU3NDA2MTI@._V1_UY209_CR0,0,140,209_AL_.jpg","The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father the ambitious celestial being Ego.",136);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(8,"Wonder Woman",7,7.5,2017,"https://m.media-amazon.com/images/M/MV5BNDFmZjgyMTEtYTk5MC00NmY0LWJhZjktOWY2MzI5YjkzODNlXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UY209_CR0,0,140,209_AL_.jpg","When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.",141);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(9,"Thor:Ragnarok",7,7.9,2017,"https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_UY209_CR0,0,140,209_AL_.jpg","Thor is imprisoned on the planet Sakaar, and must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.",130);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(10,"Doctor Strange" ,7,7.5,2016,"https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_UY209_CR0,0,140,209_AL_.jpg","While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",115);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(11,"Knocked up",7,7,2007,"https://m.media-amazon.com/images/M/MV5BNzgzYjMzMWItNDFiYi00ZjhkLWIyMzYtZGRlY2FmNzkwNjRhL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY209_CR0,0,140,209_AL_.jpg","For fun-loving party animal Ben Stone, the last thing he ever expected was for his one-night stand to show up on his doorstep eight weeks later to tell him she's pregnant with his child.",129);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(12,"She's the Man",6,6.4,2006,"https://m.media-amazon.com/images/M/MV5BNTE0NDk1YzAtNTUwZC00NmViLWI3YjgtY2ZjYWI2YjYzZjkyXkEyXkFqcGdeQXVyMTkzODUwNzk@._V1_UY209_CR1,0,140,209_AL_.jpg","When her brother decides to ditch for a couple weeks, Viola heads over to his elite boarding school, disguised as him, and proceeds to fall for one of his soccer teammates, and soon learns she's not the only one with romantic troubles.",105);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(13,"Love Actually",7,7.6,2003,"https://m.media-amazon.com/images/M/MV5BMTY4NjQ5NDc0Nl5BMl5BanBnXkFtZTYwNjk5NDM3._V1_UY209_CR0,0,140,209_AL_.jpg","Follows the lives of eight very different couples in dealing with their love lives in various loosely interrelated tales all set during a frantic month before Christmas in London, England.",135);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(14,"50 First Dates",6,6.8,2004,"https://m.media-amazon.com/images/M/MV5BMjAwMzc4MDgxNF5BMl5BanBnXkFtZTYwNjUwMzE3._V1_UY209_CR0,0,140,209_AL_.jpg","Henry Roth is a man afraid of commitment up until he meets the beautiful Lucy. They hit it off and Henry think he's finally found the girl of his dreams, until he discovers she has short-term memory loss and forgets him the next day.",99);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(15,"Us",7,7.4,2019,"https://m.media-amazon.com/images/M/MV5BZTliNWJhM2YtNDc1MC00YTk1LWE2MGYtZmE4M2Y5ODdlNzQzXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_UX140_CR0,0,140,209_AL_.jpg","A family's serene beach vacation turns to chaos when their doppelgängers appear and begin to terrorize them",116);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(16,"The Golden Glove",6,6.7,2019,"https://m.media-amazon.com/images/M/MV5BYTU3YzgwNTgtN2IyOS00YzY5LWFiMzctMWYzZmY5Y2ZjZjJlXkEyXkFqcGdeQXVyMTQ0MzMwNQ@@._V1_UY209_CR0,0,140,209_AL_.jpg","A serial killer strikes fear in the hearts of residents of Hamburg during the early 1970s.",115);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(17,"Hereditary",7,7.3,2018,"https://m.media-amazon.com/images/M/MV5BOTU5MDg3OGItZWQ1Ny00ZGVmLTg2YTUtMzBkYzQ1YWIwZjlhXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_UY209_CR0,0,140,209_AL_.jpg","After the family matriarch passes away, a grieving family is haunted by tragic and disturbing occurrences, and begin to unravel dark secrets",127);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(18,"Halloween",6,6.7,2018,"https://m.media-amazon.com/images/M/MV5BMmMzNjJhYjUtNzFkZi00MWQ4LWJiMDEtYWM0NTAzNGZjMTI3XkEyXkFqcGdeQXVyOTE2OTMwNDk@._V1_UY209_CR0,0,140,209_AL_.jpg","Laurie Strode confronts her long-time foe Michael Myers, the masked figure who has haunted her since she narrowly escaped his killing spree on Halloween night four decades ago.",106);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(19,"Climax",7,7.3,2018,"https://m.media-amazon.com/images/M/MV5BMjllYmQ2OGQtN2IxZC00ODJiLWI4NjQtYmNlZjYzNzUzYjkyXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_UY209_CR7,0,140,209_AL_.jpg","French dancers gather in a remote, empty school building to rehearse on a wintry night. The all-night celebration morphs into a hallucinatory nightmare when they learn their sangria is laced with LSD.",97);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(20,"Dr. Strangelove",7,8.4,1964,"https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX182_CR0,0,182,268_AL_.jpg","An insane general triggers a path to nuclear holocaust that a War Room full of politicians and generals frantically tries to stop.",95);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(21,"Citizen Kane",7,8.3,1941,"https://m.media-amazon.com/images/M/MV5BYjBiOTYxZWItMzdiZi00NjlkLWIzZTYtYmFhZjhiMTljOTdkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX667_CR0,0,667,999_AL_.jpg","Following the death of a publishing tycoon, news reporters scramble to discover the meaning of his final utterance",119);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(22,"Shin Godzilla",9,6.7,2016,"https://m.media-amazon.com/images/M/MV5BODQ4ZmIzNWMtY2NiYi00MmM1LWFjMGQtMDE0Nzc1NzhjNjEyXkEyXkFqcGdeQXVyNDUwNzM4MzQ@._V1_UY268_CR4,0,182,268_AL_.jpg","Japan is plunged into chaos upon the appearance of a giant monster.",120);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(23,"The Hogfather",8,7.6,2006,"https://m.media-amazon.com/images/M/MV5BOTMwNWMxNmUtZjQyOS00YjVhLTk2ODktOWUzZWYyNTZkYjBkXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg","It's Hogswatch (equivalent to Christmas) on the Discworld and the Hogfather has gone missing, requiring Death to take his place while his granddaughter Susan endeavors to find out what has happened",189);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(24,"Bill and Ted’s Excellent Adventure",10,6.9,1989,"https://m.media-amazon.com/images/M/MV5BMTk3Mjk5MzI3OF5BMl5BanBnXkFtZTcwMTY4MzcyNA@@._V1_UX182_CR0,0,182,268_AL_.jpg","Two seemingly dumb teens set off on a quest to prepare the ultimate historical presentation with the help of a time machine.",90);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(25,"Spaceballs",7,7.1,1987,"https://m.media-amazon.com/images/M/MV5BMjVjOGQ0OTctNDhkZC00ZGNiLWI2ZGEtYjZlMWZjOTlkNDlhXkEyXkFqcGdeQXVyNjg1MjEwOTM@._V1_UX182_CR0,0,182,268_AL_.jpg","A rogue star pilot and his trusty sidekick must come to the rescue of a Princess and save the galaxy from a ruthless race of beings known as Spaceballs.",96);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(26,"Galaxy Quest",7,7.3,1999,"https://m.media-amazon.com/images/M/MV5BNmZlNTY5YjQtZTU5ZC00MzcyLWI1NDMtNjA0ZjQxMmQwYjJmL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UY268_CR3,0,182,268_AL_.jpg","The alumni cast of a space opera television series have to play their roles as the real thing when an alien race needs their help. However, they also have to defend both Earth and the alien race from a reptilian warlord.",102);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(27,"Ant-man",8,7.3,2015,"https://m.media-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_UX182_CR0,0,182,268_AL_.jpg","Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.",87);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(28,"Captain Marvel",8,7.2,2019,"https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_UX182_CR0,0,182,268_AL_.jpg","Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",123);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(29,"La La Land",9,8,2016,"https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_UX182_CR0,0,182,268_AL_.jpg","While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",128);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(30,"Singin' in the Rain",6,8.3,1952,"https://m.media-amazon.com/images/M/MV5BMWUyNjQ5MTAtNDJhYS00MWQ0LTk2ZTAtZmE4MWNlMjMwMzg3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX182_CR0,0,182,268_AL_.jpg","A silent film production company and cast make a difficult transition to sound.",103);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(31,"Jiro Dreams of Sushi",6,7.9,2011,"https://m.media-amazon.com/images/M/MV5BMTA5NzQzODUxOTheQTJeQWpwZ15BbWU3MDIwODg1MDc@._V1_UY268_CR5,0,182,268_AL_.jpg","A documentary on 85-year-old sushi master Jiro Ono, his renowned Tokyo restaurant, and his relationship with his son and eventual heir, Yoshikazu.",81);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(32,"Fellowship of the Ring",8,8.8,2001,"https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UX182_CR0,0,182,268_AL_.jpg","A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",178);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(33,"Two Towers",8,8.7,2002,"https://m.media-amazon.com/images/M/MV5BNGE5MzIyNTAtNWFlMC00NDA2LWJiMjItMjc4Yjg1OWM5NzhhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY268_CR0,0,182,268_AL_.jpg","While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",179);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(34,"Return of the King",9,8.9,2003,"https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX182_CR0,0,182,268_AL_.jpg","Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",221);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(35,"The Manchurian Candidate",6,6.6,2004,"https://m.media-amazon.com/images/M/MV5BZDU2YjA4MmItODk0OS00OTllLWFmNzUtMTg2ZmM3YWYzOGFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY268_CR2,0,182,268_AL_.jpg","In the midst of the Gulf War, soldiers are kidnapped and brainwashed for sinister purposes.",129);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(36,"The Maltese Falcon",7,8.1,1941,"https://m.media-amazon.com/images/M/MV5BZjIwNGM1ZTUtOThjYS00NDdiLTk2ZDYtNGY5YjJkNzliM2JjL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_UX182_CR0,0,182,268_AL_.jpg","A private detective takes on a case that involves him with three eccentric criminals, a gorgeous liar, and their quest for a priceless statuette.",100);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(37,"Close Encounters of the Third Kind",7,7.7,1977,"https://m.media-amazon.com/images/M/MV5BMjM1NjE5NjQxN15BMl5BanBnXkFtZTgwMjYzMzQxMDE@._V1_UX182_CR0,0,182,268_AL_.jpg","Roy Neary, an electric lineman, watches how his quiet and ordinary daily life turns upside down after a close encounter with a UFO.",138);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(38,"Hellboy",9,6.9,2004,"https://m.media-amazon.com/images/M/MV5BNTc1ZWY0ZTEtZTVmNi00MTg0LTg4NmQtZTI4OWNiMmQ0MWZkXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_UY268_CR6,0,182,268_AL_.jpg","A demon, raised from infancy after being conjured by and rescued from the Nazis, grows up to become a defender against the forces of darkness.",122);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(39,"The Terminator",8,8,1984,"https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX182_CR0,0,182,268_AL_.jpg","A seemingly indestructible android is sent from 2029 to 1984 to assassinate a waitress, whose unborn son will lead humanity in a war against the machines, while a soldier from that war is sent to protect her at all costs.",107);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(40,"The Fifth Element",9,7.7,1997,"https://m.media-amazon.com/images/M/MV5BZWFjYmZmZGQtYzg4YS00ZGE5LTgwYzAtZmQwZjQ2NDliMGVmXkEyXkFqcGdeQXVyNTUyMzE4Mzg@._V1_UY268_CR2,0,182,268_AL_.jpg","In the colorful future, a cab driver unwittingly becomes the central figure in the search for a legendary cosmic weapon to keep Evil and Mr. Zorg at bay.",126);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(41,"Logan'Run",7,6.8,1976,"https://m.media-amazon.com/images/M/MV5BMjA2NTI4NDY1MF5BMl5BanBnXkFtZTgwMTg0NjAxMDE@._V1_UX182_CR0,0,182,268_AL_.jpg","An idyllic science fiction future has one major drawback: life must end at the age of thirty.",119);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(42,"Soylent Green",6,7.1,1973,"https://m.media-amazon.com/images/M/MV5BMjMwNDM0ZDUtZWE1OS00MWI1LTgxZDAtNTAzYjExZGI0MjdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg","In the world ravaged by the greenhouse effect and overpopulation, an NYPD detective investigates the murder of a big company CEO.",97);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(43,"Planet of the Apes",7,8,1968,"https://m.media-amazon.com/images/M/MV5BMTg0NjUwMzg5NF5BMl5BanBnXkFtZTgwNDQ0NjcwMTE@._V1_UX182_CR0,0,182,268_AL_.jpg","An astronaut crew crash-lands on a planet in the distant future where intelligent talking apes are the dominant species, and humans are the oppressed and enslaved.",118);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(44,"10 Things I Hate About You",8,7.3,1999,"https://m.media-amazon.com/images/M/MV5BMmVhZjhlZDYtMDAwZi00MDcyLTgzOTItOWNiZjY0YmE0MGE0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg","A pretty, popular teenager can't go out on a date until her ill-tempered older sister does.",97);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(45,"Total Recall",8,7.5,1990,"https://m.media-amazon.com/images/M/MV5BYzU1YmJjMGEtMjY4Yy00MTFlLWE3NTUtNzI3YjkwZTMxZjZmXkEyXkFqcGdeQXVyNDc2NjEyMw@@._V1_UX182_CR0,0,182,268_AL_.jpg","When a man goes for virtual vacation memories of the planet Mars, an unexpected and harrowing series of events forces him to go to the planet for real - or does he?",93);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(46,"Häxan",8,7.7,1922,"https://m.media-amazon.com/images/M/MV5BNGJjOWY1NDUtZGEyZC00Y2VmLWIzZWUtZDRmODYwYmQzN2VmXkEyXkFqcGdeQXVyNDE5MTU2MDE@._V1_UY268_CR1,0,182,268_AL_.jpg","Fictionalized documentary showing the evolution of witchcraft, from its pagan roots to its confusion with hysteria in modern Europe.",91);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(47,"The Lost Boys",8,7.3,1987,"https://m.media-amazon.com/images/M/MV5BMWEzNmUxZTMtZjY0My00OGNmLWIyNDctODM2YzZjM2YwZWEwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR0,0,182,268_AL_.jpg","After moving to a new town, two brothers discover that the area is a haven for vampires.",97);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(48,"Much Ado About Nothing",8,7.2,2012,"https://m.media-amazon.com/images/M/MV5BMTgxNjQ0MjAwMl5BMl5BanBnXkFtZTcwNjI1NDEyOQ@@._V1_UY268_CR9,0,182,268_AL_.jpg","A modern retelling of Shakespeare's classic comedy about two pairs of lovers with different takes on romance and a way with words.",109);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(49,"The Princess Bride",10,8.1,1987,"https://m.media-amazon.com/images/M/MV5BMGM4M2Q5N2MtNThkZS00NTc1LTk1NTItNWEyZjJjNDRmNDk5XkEyXkFqcGdeQXVyMjA0MDQ0Mjc@._V1_UX182_CR0,0,182,268_AL_.jpg","While home sick in bed, a young boy's grandfather reads him the story of a farmboy-turned-pirate who encounters numerous obstacles, enemies and allies in his quest to be reunited with his true love.",98);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(50,"Fight Club",9,8.8,1999,"https://m.media-amazon.com/images/M/MV5BMjJmYTNkNmItYjYyZC00MGUxLWJhNWMtZDY4Nzc1MDAwMzU5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX182_CR0,0,182,268_AL_.jpg","An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",139);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(51,"A Trip to the Moon",8,8.2,1902,"https://m.media-amazon.com/images/M/MV5BMzcyYzhlMzctYjg1NS00ODJlLTkxOTUtYmQ4YjgxMWY5MGFlXkEyXkFqcGdeQXVyNDE5MTU2MDE@._V1_UY268_CR1,0,182,268_AL_.jpg","A group of astronomers go on an expedition to the Moon.",13);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(52,"Nosferatu",4,8,1922,"https://m.media-amazon.com/images/M/MV5BMTAxYjEyMTctZTg3Ni00MGZmLWIxMmMtOGM2NTFiY2U3MmExXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX182_CR0,0,182,268_AL_.jpg","Vampire Count Orlok expresses interest in a new residence and real estate agent Hutter's wife.",81);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(53,"Vicious Lips",7,5.4,1986,"https://m.media-amazon.com/images/M/MV5BMDhjN2M0ODAtNzFiMy00YjQ0LWI2ZmEtZjNhYzQ3MzY2ZmQ2XkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_UX182_CR0,0,182,268_AL_.jpg","Sometime in the distant future, a fledgling band gets an opportunity for a breakthrough, if they can make it in time to a faraway planet to perform in a very popular club.",84);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(54,"Heavy Metal",8,6.7,1981,"https://m.media-amazon.com/images/M/MV5BOTc2NzM1ODgtM2RkYi00M2U4LWE4NzEtMDMzZGUzYmI1ZDUzL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg","A glowing green orb - which embodies ultimate evil - terrorizes a young girl with an anthology of bizarre and fantastic stories of dark fantasy, eroticism and horror.",86);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(55,"The Shamer's Daughter",8,6,2015,"https://m.media-amazon.com/images/M/MV5BMTY4NTQyNzE1Nl5BMl5BanBnXkFtZTgwMDQ3OTc0MzE@._V1_UX182_CR0,0,182,268_AL_.jpg","The Shamer's daughter, Dina, has unwillingly inherited her mother's supernatural ability. She can look straight into the soul of other people, making them feel ashamed of themselves.",96);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(56,"Night on the Galactic Railroad",7,7.2,1985,"https://m.media-amazon.com/images/M/MV5BNGU4OWNiOGYtZjE2MS00YTFjLWE3OGItMWNjYTRkMjNjYThkXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UY268_CR3,0,182,268_AL_.jpg","Two kittens go on a metaphysical journey on a magical railroad train.",93);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(57,"Voyage to the Planet of Prehistoric Women",3,2.8,1968,"https://m.media-amazon.com/images/M/MV5BMTQ3MDk1MjM1MV5BMl5BanBnXkFtZTgwMjcwNDUzMzE@._V1_UX182_CR0,0,182,268_AL_.jpg","Astronauts landing on Venus encounter dangerous creatures and almost meet some sexy Venusian women who like to sun-bathe in hip-hugging skin-tight pants and seashell brassieres.",78);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(58,"The Good, The Bad, and the Ugly",7,8.9,1966,"https://m.media-amazon.com/images/M/MV5BOTQ5NDI3MTI4MF5BMl5BanBnXkFtZTgwNDQ4ODE5MDE@._V1_UX182_CR0,0,182,268_AL_.jpg","A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",178);
insert into movies(movie_id, title, user_rate, imdb_rate, years,img_url,plot,runtime) values(59,"The Silence of the Lambs",8,8.6,1991,"https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg","A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",118);
